### ISSUE TITLE
Security Issue #SMA-01

### ISSUE THREAD

**Issue by ClementNerma** [ClementNerma/NearOS#1]
A major security issue was found in NearOS : 
Applications can access to their parent's frame by using window.frameElement. This permit to take control of the entire system.

This issue will be fixed in the next days.

**Comment by ghost** [comment]
Peut être que tu peux utiliser l'attribut "sandbox" sur tes iframes ;)

**Comment by ClementNerma** [comment]
Question closed on OpenClassrooms :
When iframe is isolated with the HTML5 Sandbox attribute (using "allow-scripts") flag, system (main) frame can't communicate anymore with any child iframe.
